# Configure.
language: python
python: 3.5
sudo: false

# Run.
install: pip install appveyor-artifacts coveralls tox
script: tox -e lint,py35,py34,py33,pypy3,pypy,py27,py26,docs
after_success:
  - mv .coverage .coverage.travis
  - appveyor-artifacts -mi download
  - coverage combine
  - coveralls

# Deploy.
deploy:
  provider: pypi
  user: Robpol86
  password:
    secure:
      "aj+Hl25+NbtmKpHcqxxNJhaMmawgzEPdLX+NwxwAZuTrvUCdiMtYhF9qxN0USHIlXSGDNc\
      7ua6nNpYPhjRv7j5YM4uLlK+4Fv/iU+iQcVfy89BS4vlXzUoje6nLIhogsxytb+FjdGZ0PK\
      JzzxfYr0relUjui/gPYmTQoZ1IiT8A="
  on:
    tags: true
