language: python

python:
  - '2.6'
  - '2.7'
  - 'pypy'
  - '3.3'
  - '3.4'

install: 'pip install .'

before_script: 'pip install python-coveralls colorclass'

script:
  - 'python setup.py test'
  - 'python example1.py'
  - 'python example2.py'
  - 'python example3.py'

after_success: 'coveralls -i'
